import type { StoredCourse } from "./courses-store";

/**
 * Built-in seed courses — the always-available source of truth for the public
 * pages. The site previously depended entirely on a free third-party cloud
 * store (jsonblob) for course data, which meant a partial/stale overwrite left
 * visitors with an empty or truncated list. These 15 courses are shipped with
 * the app, so public pages always have something to show. The shared store and
 * backend API still overlay on top when they have newer admin data.
 */

const img = (n: string) => `/images/courses/${n}`;

export const SEED_COURSES: StoredCourse[] = [
  {
    id: "course-odoo-technical",
    title: "Odoo Technical",
    duration: "4 months",
    category: "ERP",
    categoryId: "ERP",
    status: "active",
    imageUrl: img("odooTechnical.jpg"),
    rating: 4.8,
    shortDescription:
      "Learn Odoo development: module creation, customization, API integration and advanced technical concepts for real business systems.",
    learningOutcomes: [
      "Python fundamentals for Odoo",
      "Odoo architecture & ORM",
      "Module & view creation",
      "Security & access rights",
      "API & web services",
      "Deployment & upgrade",
    ],
    priceOriginal: 20000,
    priceDiscounted: 3500,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 1,
    level: "Intermediate",
    mode: "Online",
  },
  {
    id: "course-odoo-functional",
    title: "Odoo Functional",
    duration: "3 months",
    category: "ERP",
    categoryId: "ERP",
    status: "active",
    imageUrl: img("odooErpFunction.jpg"),
    rating: 4.7,
    shortDescription:
      "Master Odoo ERP functional modules — Sales, Purchase, Inventory and Accounting — and configure Odoo for real business needs.",
    learningOutcomes: [
      "Introduction to Odoo ERP",
      "Sales management",
      "Purchase management",
      "Inventory management",
      "Accounting basics",
      "CRM integration",
    ],
    priceOriginal: 18000,
    priceDiscounted: 3000,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 2,
    level: "Beginner",
    mode: "Online",
  },
  {
    id: "course-full-stack",
    title: "Full-Stack Web Development",
    duration: "6 months",
    category: "Development",
    categoryId: "Development",
    status: "active",
    imageUrl: img("fullStuck.jpg"),
    rating: 4.9,
    shortDescription:
      "Complete full-stack bootcamp: frontend, backend, database and deployment with real-world projects and mentorship.",
    learningOutcomes: [
      "HTML, CSS & JavaScript",
      "React.js frontend",
      "Node.js backend",
      "MongoDB & databases",
      "REST APIs",
      "Deployment & Git",
    ],
    priceOriginal: 30000,
    priceDiscounted: 5000,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 3,
    level: "Beginner",
    mode: "Online",
  },
  {
    id: "course-n8n-automation",
    title: "n8n Automation Bootcamp",
    duration: "8 weeks",
    category: "Automation",
    categoryId: "Automation",
    status: "active",
    imageUrl: img("n8bAutomation.jpg"),
    rating: 4.6,
    shortDescription:
      "Automate workflows with n8n — connect apps, APIs and webhooks to save hours of manual work.",
    learningOutcomes: [
      "Introduction to n8n",
      "Workflow creation",
      "API integration",
      "Webhooks",
      "Email automation",
      "Custom nodes",
    ],
    priceOriginal: 10000,
    priceDiscounted: 1800,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 4,
    level: "Beginner",
    mode: "Online",
  },
  {
    id: "course-frontend-fundamentals",
    title: "Frontend Fundamentals",
    duration: "6 weeks",
    category: "Development",
    categoryId: "Development",
    status: "active",
    imageUrl: img("frontendFundamental.jpg"),
    rating: 4.7,
    shortDescription:
      "Master the building blocks of the web — HTML, CSS and JavaScript — and build responsive interfaces.",
    learningOutcomes: [
      "HTML structure & semantics",
      "CSS styling & layout",
      "Flexbox & Grid",
      "JavaScript basics",
      "DOM manipulation",
      "Responsive design",
    ],
    priceOriginal: 10000,
    priceDiscounted: 1800,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 5,
    level: "Beginner",
    mode: "Online",
  },
  {
    id: "course-backend-development",
    title: "Backend Development",
    duration: "8 weeks",
    category: "Development",
    categoryId: "Development",
    status: "active",
    imageUrl: img("backendDeve.jpg"),
    rating: 4.8,
    shortDescription:
      "Build robust server-side applications — REST APIs, databases, authentication and deployment.",
    learningOutcomes: [
      "Node.js & Express",
      "REST API design",
      "MongoDB & PostgreSQL",
      "Authentication & security",
      "Testing & debugging",
      "Deployment",
    ],
    priceOriginal: 15000,
    priceDiscounted: 2500,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 6,
    level: "Intermediate",
    mode: "Online",
  },
  {
    id: "course-data-science",
    title: "Data Science & Machine Learning",
    duration: "4 months",
    category: "AI",
    categoryId: "AI",
    status: "active",
    imageUrl: img("dataSaince.jpg"),
    rating: 4.8,
    shortDescription:
      "Master data analysis, visualization and machine learning with hands-on projects and real datasets.",
    learningOutcomes: [
      "Data analysis & cleaning",
      "Data visualization",
      "Statistics fundamentals",
      "Machine learning models",
      "Python for data science",
      "Capstone project",
    ],
    priceOriginal: 25000,
    priceDiscounted: 4000,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 7,
    level: "Intermediate",
    mode: "Online",
  },
  {
    id: "course-python",
    title: "Python Programming",
    duration: "3 months",
    category: "Development",
    categoryId: "Development",
    status: "active",
    imageUrl: img("phyton.jpg"),
    rating: 4.6,
    shortDescription:
      "Comprehensive Python course from basics to advanced — data structures, OOP, files and error handling.",
    learningOutcomes: [
      "Python basics",
      "Data structures",
      "Functions & modules",
      "File handling",
      "Error handling",
      "OOP in Python",
    ],
    priceOriginal: 12000,
    priceDiscounted: 2000,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 8,
    level: "Beginner",
    mode: "Online",
  },
  {
    id: "course-flutter",
    title: "Flutter (Mobile App Development)",
    duration: "4 months",
    category: "Development",
    categoryId: "Development",
    status: "active",
    imageUrl: img("flutter.jpg"),
    rating: 4.5,
    shortDescription:
      "Build beautiful cross-platform mobile apps for Android and iOS with Flutter and Dart.",
    learningOutcomes: [
      "Dart fundamentals",
      "Flutter widgets & UI",
      "State management",
      "Navigation & routing",
      "API integration",
      "App publishing",
    ],
    priceOriginal: 18000,
    priceDiscounted: 3000,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 9,
    level: "Intermediate",
    mode: "Online",
  },
  {
    id: "course-cybersecurity",
    title: "Cybersecurity",
    duration: "4 months",
    category: "IT",
    categoryId: "IT",
    status: "active",
    imageUrl: img("cybercecurty.jpg"),
    rating: 4.7,
    shortDescription:
      "Learn to protect systems and data — network security, ethical hacking, threat detection and defense.",
    learningOutcomes: [
      "Network security basics",
      "Ethical hacking",
      "Threat detection",
      "Cryptography",
      "Security tools",
      "Incident response",
    ],
    priceOriginal: 18000,
    priceDiscounted: 3000,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 10,
    level: "Intermediate",
    mode: "Online",
  },
  {
    id: "course-accounting",
    title: "Accounting (Peachtree, Excel, QuickBooks)",
    duration: "3 months",
    category: "Business",
    categoryId: "Business",
    status: "active",
    imageUrl: img("accounting.jpg"),
    rating: 4.4,
    shortDescription:
      "Practical accounting with Peachtree, QuickBooks and Excel — journal entries, ledgers, reports and payroll.",
    learningOutcomes: [
      "Accounting fundamentals",
      "Peachtree mastery",
      "QuickBooks mastery",
      "Excel for accountants",
      "Financial reports",
      "Payroll",
    ],
    priceOriginal: 15000,
    priceDiscounted: 2500,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 11,
    level: "Beginner",
    mode: "Online",
  },
  {
    id: "course-digital-marketing",
    title: "Digital Marketing",
    duration: "2 months",
    category: "Business",
    categoryId: "Business",
    status: "active",
    imageUrl: img("digitalMarketing.jpg"),
    rating: 4.3,
    shortDescription:
      "Grow brands online — SEO, social media, content, email and paid ads with practical campaigns.",
    learningOutcomes: [
      "SEO & keyword research",
      "Social media marketing",
      "Content strategy",
      "Email marketing",
      "Google & Meta ads",
      "Analytics & reporting",
    ],
    priceOriginal: 15000,
    priceDiscounted: 2500,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 12,
    level: "Beginner",
    mode: "Online",
  },
  {
    id: "course-basic-computer",
    title: "Basic Computer Skills",
    duration: "1 month",
    category: "IT",
    categoryId: "IT",
    status: "active",
    imageUrl: img("basicComputerskill.jpg"),
    rating: 4.2,
    shortDescription:
      "Get comfortable with computers — Windows, files, email, internet, Word/Excel basics and typing.",
    learningOutcomes: [
      "Computer fundamentals",
      "File management",
      "Internet & email",
      "MS Word basics",
      "MS Excel basics",
      "Online safety",
    ],
    priceOriginal: 8000,
    priceDiscounted: 1500,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 13,
    level: "Beginner",
    mode: "Online",
  },
  {
    id: "course-ielts-toefl",
    title: "IELTS, TOEFL & Duolingo Preparation",
    duration: "2 months",
    category: "Language",
    categoryId: "Language",
    status: "active",
    imageUrl: img("tofl.jpg"),
    rating: 4.5,
    shortDescription:
      "Intensive test-prep for IELTS, TOEFL and Duolingo — listening, speaking, reading, writing and strategy.",
    learningOutcomes: [
      "Test strategies & time management",
      "Listening & speaking practice",
      "Reading techniques",
      "Writing templates",
      "Mock tests & scoring",
    ],
    priceOriginal: 15000,
    priceDiscounted: 2500,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 14,
    level: "Beginner",
    mode: "Online",
  },
  {
    id: "course-microsoft-office",
    title: "Microsoft Office 365",
    duration: "1 month",
    category: "IT",
    categoryId: "IT",
    status: "active",
    imageUrl: img("microsoft.jpg"),
    rating: 4.4,
    shortDescription:
      "Master Office 365 — Word, Excel, PowerPoint, Outlook, Teams and OneDrive for work and study.",
    learningOutcomes: [
      "Word documents & formatting",
      "Excel spreadsheets & formulas",
      "PowerPoint presentations",
      "Outlook email & calendar",
      "Teams & OneDrive",
      "Productivity tips",
    ],
    priceOriginal: 10000,
    priceDiscounted: 1800,
    startDate: "",
    createdAt: "2026-08-11T00:00:00.000Z",
    priority: 15,
    level: "Beginner",
    mode: "Online",
  },
];

export function getSeedCourseById(id: string): StoredCourse | undefined {
  return SEED_COURSES.find((c) => c.id === id);
}

export function getSeedCourseBySlug(slug: string): StoredCourse | undefined {
  const s = slug.toLowerCase();
  return (
    SEED_COURSES.find((c) => c.id === slug) ||
    SEED_COURSES.find((c) => c.title.toLowerCase() === s) ||
    SEED_COURSES.find((c) => toSlug(c.title) === toSlug(slug)) ||
    SEED_COURSES.find((c) => toSlug(c.id) === toSlug(slug))
  );
}

function toSlug(str: string): string {
  return str
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
